[package]
name = "mute-cs"
version = "0.1.0"
authors = ["keringar <git@keringar.xyz>"]

[dependencies]
actix = "0.5.5"
actix-web = "0.4.10"
failure = "0.1.1"
serde = "1.0.37"
serde_json = "1.0.13"
env_logger = "0.5.6"
