[package]
name = "mute-cs"
version = "0.1.0"
authors = ["keringar <git@keringar.xyz>"]

[dependencies]
hyper = "0.11.25"
futures = "0.1.21"
tokio = "0.1.5"
serde = "1.0.37"
serde_json = "1.0.13"
failure = "0.1.1"
